server:
  port: 3000


wx:
  config:
    originalid: gh_ce466ae81f85
    appid:  wx501a1603b0e3c03d
    AppSecret: 78ec62f38f47c552283ed449d4574c2a
    token: theRegion
    auth:
      defaultBase64EncodedSecretKey: B*B^D%fe